version: '2'

services:
  ### Django Jenkins
  django_jenkins_host:
    build: ${PROJECT_PATH}/django_jenkins/django_jenkins
    volumes:
      - ${PROJECT_PATH}/django_jenkins/django_jenkins:/opt/app
    ports:
      - "8086:8080"
    links:
      - postgres_jenkins
    env_file:
      - ./jenkins.env
    networks:
      default:
        aliases:
          - django-jenkins.local
  postgres_jenkins:
    image: onjin/alpine-postgres:9.3
    ports:
      - "5433:5432"
    volumes:
      - ${PROJECT_PATH}/jenkins-docker/database:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=django_jenkins_db
    networks:
      default:
        aliases:
        - postgres.local
networks:
  default:
